global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "gotunnel_rules.yml"

scrape_configs:
  # GoTunnel Server metrics
  - job_name: 'gotunnel-server'
    static_configs:
      - targets: ['gotunnel-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # GoTunnel Client metrics (if exposed)
  - job_name: 'gotunnel-clients'
    static_configs:
      - targets: ['localhost:8081', 'localhost:8082']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093 